// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.6.0

//# unitInfo: Provides: H42n42
//# unitInfo: Requires: Eliom_client, Eliom_client_core, Eliom_content, Eliom_registration, Eliom_service, Lwt
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, cst_h42n42_eliom = "h42n42.eliom";
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   function caml_call3(f, a0, a1, a2){
    return (f.l >= 0 ? f.l : f.l = f.length) == 3
            ? f(a0, a1, a2)
            : runtime.caml_call_gen(f, [a0, a1, a2]);
   }
   function caml_call10(f, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9){
    return (f.l >= 0 ? f.l : f.l = f.length) == 10
            ? f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9)
            : runtime.caml_call_gen
              (f, [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9]);
   }
   function caml_call11(f, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10){
    return (f.l >= 0 ? f.l : f.l = f.length) == 11
            ? f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10)
            : runtime.caml_call_gen
              (f, [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    cst = "!",
    eliom_compilation_unit_id_eZ0b = "eZ0bjX",
    global_data_path = [0, [0, "__global_data__", 0]],
    Eliom_content = global_data.Eliom_content,
    Eliom_service = global_data.Eliom_service,
    Lwt = global_data.Lwt,
    Eliom_client = global_data.Eliom_client,
    Eliom_registration = global_data.Eliom_registration,
    Eliom_client_core = global_data.Eliom_client_core,
    application_name = caml_call1(Eliom_client[18], 0),
    App =
      caml_call1
       (Eliom_registration[4], [0, application_name, global_data_path]);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   caml_call1(Eliom_client[19], 0);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   caml_call1(Eliom_client_core[56][2], eliom_compilation_unit_id_eZ0b);
   var
    main_service =
      caml_call3
       (Eliom_client_core[56][5],
        [0, "main_service"],
        [0,
         [0,
          [0, cst_h42n42_eliom, 24, 889, 917],
          [0, cst_h42n42_eliom, 24, 889, 917]]],
        "eZ0bjX1"),
    cst_world = "world",
    cst_Hello = "Hello",
    _b_ = [0, "css", [0, "h42n42.css", 0]],
    cst_h42n42 = "h42n42";
   function _a_(param, _c_){
    var
     _d_ = [0, caml_call1(Eliom_content[3][1][219], cst), 0],
     _e_ = [0, caml_call1(Eliom_content[3][1][219], cst_world), 0],
     _f_ = [0, caml_call2(Eliom_content[3][1][268], 0, _e_), _d_],
     _g_ = [0, caml_call1(Eliom_content[3][1][219], cst_Hello), _f_],
     _h_ = [0, caml_call2(Eliom_content[3][1][230], 0, _g_), 0],
     _i_ = caml_call2(Eliom_content[3][1][224], 0, _h_),
     _j_ = caml_call1(Eliom_service[5], 0),
     _k_ =
       caml_call10(Eliom_content[3][1][344], 0, 0, 0, _j_, 0, 0, 0, 0, 0, _b_),
     _l_ = [0, caml_call3(Eliom_content[3][1][346], 0, _k_, 0), 0],
     _m_ = caml_call1(Eliom_content[3][1][219], cst_h42n42),
     _n_ = caml_call2(Eliom_content[3][1][223], 0, _m_),
     _o_ = caml_call3(Eliom_content[3][1][221], 0, _n_, _l_),
     _p_ = caml_call3(Eliom_content[3][1][220], 0, _o_, _i_);
    return caml_call1(Lwt[4], _p_);
   }
   caml_call11(App[2], 0, 0, 0, 0, 0, 0, 0, 0, main_service, 0, _a_);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   var H42n42 = [0];
   runtime.caml_register_global(16, H42n42, "H42n42");
   return;
  }
  (globalThis));
