version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: $PWD
        target: /usr/app
    # ports:
      # - '8080:8080'
    # command: make test.byte 
